# Generated by Django 5.1.5 on 2025-02-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_userprofile_address_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
