# Generated by Django 5.1.6 on 2025-02-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_server_app', '0002_taskstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
